---
title: "Hub spots"
author: "Connor"
date: "November 8, 2016"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## The default point is the centroid point of population

```{r eruptions, echo=FALSE, message=FALSE}
library(tidyverse)
library(USAboundaries)
library(maptools)
library(sp)
library(broom)
library(ggthemes)
library(broom)
library(ggplot2)

counties_shp <- us_counties() 
centroids <- coordinates(counties_shp)
counties_data <- counties_shp@data %>%
  mutate(centroidlong = coordinates(counties_shp)[,1]) %>%
  mutate(centroidlat = coordinates(counties_shp)[,2]) 
counties_polygon <- tidy(counties_shp, region="geoid")
counties <- left_join(counties_polygon, counties_data, by=c("id"="geoid"))


counties <- counties %>%
  filter( !state_name %in% c("Alaska", "Hawaii", "Puerto Rico"))


inputPanel(
  sliderInput("long", label = "Longitude",
              min = -125, max = -66, value = -92, step = 1),
  
  sliderInput("lat", label = "Latitude",
              min = 24, max = 50, value = 38, step = 1)
)

renderPlot({
  counties <- counties %>%
    filter( !state_name %in% c("Alaska", "Hawaii", "Puerto Rico"))

  countydistances <- counties %>%
    mutate(dist = (sqrt((centroidlong-input$long)^2 + (centroidlat-input$lat)^2)))
  
  ggplot(countydistances, aes(x=long, y=lat, group = group, fill = dist)) +
  geom_polygon() +
  geom_path(color = "darkslateblue", size = .1)+
  scale_fill_gradient(low="white", high="darkgreen") + 
  annotate("point", x=(input$long), y=input$lat, col="violetred2", size=3) +
  coord_map()
})
```




